party_mode:
  description: Change fan speed for limited time. Deprecated, use start_party_mode and stop_party_mode instead.
  fields:
    entity_id:
      description: Name of the entity.
      example: "fan.helios"
    speed:
      description: "Boost speed. Available: basic, rated, intensive, maximum"
      example: intensive
    duration:
      description: Duration in minutes
      example: 60
start_party_mode:
  description: Starts the party mode for a limited time.
  fields:
    entity_id:
      description: Name of the entity.
      example: "fan.helios"
    speed:
      description: "Boost speed. Available: basic, rated, intensive, maximum"
      example: intensive
    duration:
      description: Duration in minutes
      example: 60
stop_party_mode:
  description: Stops the party mode.
  fields:
    entity_id:
      description: Name of the entity.
      example: "fan.helios"
